//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by UrhoAssetGenerator.tt, Version=1.
// 

using System;

namespace SamplyGame
{
	public static class Assets 
	{

		public static class Fonts
		{
			public const string AnonymousPro = "Fonts/Anonymous Pro.ttf";
			public const string Font = "Fonts/Font.ttf";
		}

		public static class Materials
		{
			public const string DefaultGrey = "Materials/DefaultGrey.xml";
			public const string Apple = "Materials/Apple.xml";
			public const string Enemy3 = "Materials/Enemy3.xml";
			public const string Enemy3weapon = "Materials/Enemy3weapon.xml";
			public const string Enemy4DD = "Materials/Enemy4DD.xml";
			public const string Grass = "Materials/Grass.xml";
			public const string MachineGun = "Materials/MachineGun.xml";
			public const string Monkey = "Materials/Monkey.xml";
			public const string Player1D = "Materials/Player1D.xml";
			public const string PyramidMaterial = "Materials/PyramidMaterial.xml";
		}

		public static class Models
		{
			public const string Box = "Models/Box.mdl";
			public const string Cone = "Models/Cone.mdl";
			public const string Cylinder = "Models/Cylinder.mdl";
			public const string Dome = "Models/Dome.mdl";
			public const string LinePrimitives_Basis = "Models/LinePrimitives/Basis.mdl";
			public const string LinePrimitives_Box1x1x1 = "Models/LinePrimitives/Box1x1x1.mdl";
			public const string LinePrimitives_CubicBezier = "Models/LinePrimitives/CubicBezier.mdl";
			public const string LinePrimitives_LinearBezier = "Models/LinePrimitives/LinearBezier.mdl";
			public const string LinePrimitives_QuadraticBezier = "Models/LinePrimitives/QuadraticBezier.mdl";
			public const string LinePrimitives_UnitX = "Models/LinePrimitives/UnitX.mdl";
			public const string LinePrimitives_UnitY = "Models/LinePrimitives/UnitY.mdl";
			public const string LinePrimitives_UnitZ = "Models/LinePrimitives/UnitZ.mdl";
			public const string Plane = "Models/Plane.mdl";
			public const string Pyramid = "Models/Pyramid.mdl";
			public const string Sphere = "Models/Sphere.mdl";
			public const string Torus = "Models/Torus.mdl";
			public const string Apple = "Models/Apple.mdl";
			public const string Enemy3 = "Models/Enemy3.mdl";
			public const string Enemy3weapon = "Models/Enemy3weapon.mdl";
			public const string Enemy4 = "Models/Enemy4.mdl";
			public const string Monkey = "Models/Monkey.mdl";
			public const string Player1 = "Models/Player1.mdl";
			public const string PyramidTree = "Models/PyramidTree.mdl";
			public const string Skull = "Models/Skull.mdl";
		}

		public static class PostProcess
		{
			public const string AutoExposure = "PostProcess/AutoExposure.xml";
			public const string Bloom = "PostProcess/Bloom.xml";
			public const string BloomHDR = "PostProcess/BloomHDR.xml";
			public const string Blur = "PostProcess/Blur.xml";
			public const string ColorCorrection = "PostProcess/ColorCorrection.xml";
			public const string FXAA2 = "PostProcess/FXAA2.xml";
			public const string FXAA3 = "PostProcess/FXAA3.xml";
			public const string GammaCorrection = "PostProcess/GammaCorrection.xml";
			public const string GreyScale = "PostProcess/GreyScale.xml";
			public const string Tonemap = "PostProcess/Tonemap.xml";
		}

		public static class RenderPaths
		{
			public const string Deferred = "RenderPaths/Deferred.xml";
			public const string DeferredHWDepth = "RenderPaths/DeferredHWDepth.xml";
			public const string Forward = "RenderPaths/Forward.xml";
			public const string ForwardDepth = "RenderPaths/ForwardDepth.xml";
			public const string ForwardHWDepth = "RenderPaths/ForwardHWDepth.xml";
			public const string PBRDeferred = "RenderPaths/PBRDeferred.xml";
			public const string PBRDeferredHWDepth = "RenderPaths/PBRDeferredHWDepth.xml";
			public const string Prepass = "RenderPaths/Prepass.xml";
			public const string PrepassHDR = "RenderPaths/PrepassHDR.xml";
			public const string PrepassHWDepth = "RenderPaths/PrepassHWDepth.xml";
		}

		public static class Shaders
		{
			public const string HLSL_AutoExposure = "Shaders/HLSL/AutoExposure.hlsl";
			public const string HLSL_Basic = "Shaders/HLSL/Basic.hlsl";
			public const string HLSL_Bloom = "Shaders/HLSL/Bloom.hlsl";
			public const string HLSL_BloomHDR = "Shaders/HLSL/BloomHDR.hlsl";
			public const string HLSL_Blur = "Shaders/HLSL/Blur.hlsl";
			public const string HLSL_BRDF = "Shaders/HLSL/BRDF.hlsl";
			public const string HLSL_ColorCorrection = "Shaders/HLSL/ColorCorrection.hlsl";
			public const string HLSL_Constants = "Shaders/HLSL/Constants.hlsl";
			public const string HLSL_CopyFramebuffer = "Shaders/HLSL/CopyFramebuffer.hlsl";
			public const string HLSL_DeferredLight = "Shaders/HLSL/DeferredLight.hlsl";
			public const string HLSL_Depth = "Shaders/HLSL/Depth.hlsl";
			public const string HLSL_Fog = "Shaders/HLSL/Fog.hlsl";
			public const string HLSL_FXAA2 = "Shaders/HLSL/FXAA2.hlsl";
			public const string HLSL_FXAA3 = "Shaders/HLSL/FXAA3.hlsl";
			public const string HLSL_GammaCorrection = "Shaders/HLSL/GammaCorrection.hlsl";
			public const string HLSL_GreyScale = "Shaders/HLSL/GreyScale.hlsl";
			public const string HLSL_IBL = "Shaders/HLSL/IBL.hlsl";
			public const string HLSL_Lighting = "Shaders/HLSL/Lighting.hlsl";
			public const string HLSL_LitParticle = "Shaders/HLSL/LitParticle.hlsl";
			public const string HLSL_LitSolid = "Shaders/HLSL/LitSolid.hlsl";
			public const string HLSL_PBR = "Shaders/HLSL/PBR.hlsl";
			public const string HLSL_PBRDeferred = "Shaders/HLSL/PBRDeferred.hlsl";
			public const string HLSL_PBRLitSolid = "Shaders/HLSL/PBRLitSolid.hlsl";
			public const string HLSL_PostProcess = "Shaders/HLSL/PostProcess.hlsl";
			public const string HLSL_PrepassLight = "Shaders/HLSL/PrepassLight.hlsl";
			public const string HLSL_Samplers = "Shaders/HLSL/Samplers.hlsl";
			public const string HLSL_ScreenPos = "Shaders/HLSL/ScreenPos.hlsl";
			public const string HLSL_Shadow = "Shaders/HLSL/Shadow.hlsl";
			public const string HLSL_ShadowBlur = "Shaders/HLSL/ShadowBlur.hlsl";
			public const string HLSL_Skybox = "Shaders/HLSL/Skybox.hlsl";
			public const string HLSL_Skydome = "Shaders/HLSL/Skydome.hlsl";
			public const string HLSL_Stencil = "Shaders/HLSL/Stencil.hlsl";
			public const string HLSL_TerrainBlend = "Shaders/HLSL/TerrainBlend.hlsl";
			public const string HLSL_Text = "Shaders/HLSL/Text.hlsl";
			public const string HLSL_Tonemap = "Shaders/HLSL/Tonemap.hlsl";
			public const string HLSL_Transform = "Shaders/HLSL/Transform.hlsl";
			public const string HLSL_Uniforms = "Shaders/HLSL/Uniforms.hlsl";
			public const string HLSL_Unlit = "Shaders/HLSL/Unlit.hlsl";
			public const string HLSL_UnlitParticle = "Shaders/HLSL/UnlitParticle.hlsl";
			public const string HLSL_Urho2D = "Shaders/HLSL/Urho2D.hlsl";
			public const string HLSL_Vegetation = "Shaders/HLSL/Vegetation.hlsl";
			public const string HLSL_VegetationDepth = "Shaders/HLSL/VegetationDepth.hlsl";
			public const string HLSL_VegetationShadow = "Shaders/HLSL/VegetationShadow.hlsl";
			public const string HLSL_Water = "Shaders/HLSL/Water.hlsl";
			public const string HLSL_ClearFramebuffer = "Shaders/HLSL/ClearFramebuffer.hlsl";
		}

		public static class Techniques
		{
			public const string BasicVColUnlitAlpha = "Techniques/BasicVColUnlitAlpha.xml";
			public const string Diff = "Techniques/Diff.xml";
			public const string DiffAdd = "Techniques/DiffAdd.xml";
			public const string DiffAddAlpha = "Techniques/DiffAddAlpha.xml";
			public const string DiffAlpha = "Techniques/DiffAlpha.xml";
			public const string DiffAlphaTranslucent = "Techniques/DiffAlphaTranslucent.xml";
			public const string DiffAO = "Techniques/DiffAO.xml";
			public const string DiffAOAlpha = "Techniques/DiffAOAlpha.xml";
			public const string DiffEmissive = "Techniques/DiffEmissive.xml";
			public const string DiffEmissiveAlpha = "Techniques/DiffEmissiveAlpha.xml";
			public const string DiffEnvCube = "Techniques/DiffEnvCube.xml";
			public const string DiffEnvCubeAlpha = "Techniques/DiffEnvCubeAlpha.xml";
			public const string DiffEnvCubeAO = "Techniques/DiffEnvCubeAO.xml";
			public const string DiffEnvCubeAOAlpha = "Techniques/DiffEnvCubeAOAlpha.xml";
			public const string DiffLightMap = "Techniques/DiffLightMap.xml";
			public const string DiffLightMapAlpha = "Techniques/DiffLightMapAlpha.xml";
			public const string DiffLitParticleAlpha = "Techniques/DiffLitParticleAlpha.xml";
			public const string DiffLitParticleAlphaSoft = "Techniques/DiffLitParticleAlphaSoft.xml";
			public const string DiffLitParticleAlphaSoftExpand = "Techniques/DiffLitParticleAlphaSoftExpand.xml";
			public const string DiffMultiply = "Techniques/DiffMultiply.xml";
			public const string DiffNormal = "Techniques/DiffNormal.xml";
			public const string DiffNormalAlpha = "Techniques/DiffNormalAlpha.xml";
			public const string DiffNormalAlphaTranslucent = "Techniques/DiffNormalAlphaTranslucent.xml";
			public const string DiffNormalAO = "Techniques/DiffNormalAO.xml";
			public const string DiffNormalAOAlpha = "Techniques/DiffNormalAOAlpha.xml";
			public const string DiffNormalEmissive = "Techniques/DiffNormalEmissive.xml";
			public const string DiffNormalEmissiveAlpha = "Techniques/DiffNormalEmissiveAlpha.xml";
			public const string DiffNormalEnvCube = "Techniques/DiffNormalEnvCube.xml";
			public const string DiffNormalEnvCubeAlpha = "Techniques/DiffNormalEnvCubeAlpha.xml";
			public const string DiffNormalSpec = "Techniques/DiffNormalSpec.xml";
			public const string DiffNormalSpecAlpha = "Techniques/DiffNormalSpecAlpha.xml";
			public const string DiffNormalSpecAO = "Techniques/DiffNormalSpecAO.xml";
			public const string DiffNormalSpecAOAlpha = "Techniques/DiffNormalSpecAOAlpha.xml";
			public const string PBR_DiffNormalSpecEmissive = "Techniques/PBR/DiffNormalSpecEmissive.xml";
			public const string PBR_DiffNormalSpecEmissiveAlpha = "Techniques/PBR/DiffNormalSpecEmissiveAlpha.xml";
			public const string DiffOverlay = "Techniques/DiffOverlay.xml";
			public const string DiffSkybox = "Techniques/DiffSkybox.xml";
			public const string DiffSkyboxHDRScale = "Techniques/DiffSkyboxHDRScale.xml";
			public const string DiffSkydome = "Techniques/DiffSkydome.xml";
			public const string DiffSkyplane = "Techniques/DiffSkyplane.xml";
			public const string DiffSpec = "Techniques/DiffSpec.xml";
			public const string DiffSpecAlpha = "Techniques/DiffSpecAlpha.xml";
			public const string DiffUnlit = "Techniques/DiffUnlit.xml";
			public const string DiffUnlitAlpha = "Techniques/DiffUnlitAlpha.xml";
			public const string DiffUnlitParticleAdd = "Techniques/DiffUnlitParticleAdd.xml";
			public const string DiffUnlitParticleAddSoft = "Techniques/DiffUnlitParticleAddSoft.xml";
			public const string DiffUnlitParticleAddSoftExpand = "Techniques/DiffUnlitParticleAddSoftExpand.xml";
			public const string DiffUnlitParticleAlpha = "Techniques/DiffUnlitParticleAlpha.xml";
			public const string DiffUnlitParticleAlphaSoft = "Techniques/DiffUnlitParticleAlphaSoft.xml";
			public const string DiffUnlitParticleAlphaSoftExpand = "Techniques/DiffUnlitParticleAlphaSoftExpand.xml";
			public const string DiffVCol = "Techniques/DiffVCol.xml";
			public const string DiffVColAdd = "Techniques/DiffVColAdd.xml";
			public const string DiffVColAddAlpha = "Techniques/DiffVColAddAlpha.xml";
			public const string DiffVColMultiply = "Techniques/DiffVColMultiply.xml";
			public const string DiffVColUnlitAlpha = "Techniques/DiffVColUnlitAlpha.xml";
			public const string NoTexture = "Techniques/NoTexture.xml";
			public const string NoTextureAdd = "Techniques/NoTextureAdd.xml";
			public const string NoTextureAddAlpha = "Techniques/NoTextureAddAlpha.xml";
			public const string NoTextureAlpha = "Techniques/NoTextureAlpha.xml";
			public const string NoTextureAO = "Techniques/NoTextureAO.xml";
			public const string NoTextureAOAlpha = "Techniques/NoTextureAOAlpha.xml";
			public const string NoTextureEnvCube = "Techniques/NoTextureEnvCube.xml";
			public const string NoTextureEnvCubeAlpha = "Techniques/NoTextureEnvCubeAlpha.xml";
			public const string NoTextureEnvCubeAO = "Techniques/NoTextureEnvCubeAO.xml";
			public const string NoTextureEnvCubeAOAlpha = "Techniques/NoTextureEnvCubeAOAlpha.xml";
			public const string NoTextureMultiply = "Techniques/NoTextureMultiply.xml";
			public const string NoTextureNormal = "Techniques/NoTextureNormal.xml";
			public const string NoTextureNormalAlpha = "Techniques/NoTextureNormalAlpha.xml";
			public const string NoTextureOverlay = "Techniques/NoTextureOverlay.xml";
			public const string NoTextureUnlit = "Techniques/NoTextureUnlit.xml";
			public const string NoTextureUnlitAlpha = "Techniques/NoTextureUnlitAlpha.xml";
			public const string NoTextureUnlitVCol = "Techniques/NoTextureUnlitVCol.xml";
			public const string NoTextureVCol = "Techniques/NoTextureVCol.xml";
			public const string NoTextureVColAdd = "Techniques/NoTextureVColAdd.xml";
			public const string NoTextureVColAddAlpha = "Techniques/NoTextureVColAddAlpha.xml";
			public const string NoTextureVColMultiply = "Techniques/NoTextureVColMultiply.xml";
			public const string PBR_PBRDiff = "Techniques/PBR/PBRDiff.xml";
			public const string PBR_PBRDiffAlpha = "Techniques/PBR/PBRDiffAlpha.xml";
			public const string PBR_PBRDiffNormal = "Techniques/PBR/PBRDiffNormal.xml";
			public const string PBR_PBRDiffNormalAlpha = "Techniques/PBR/PBRDiffNormalAlpha.xml";
			public const string PBR_PBRDiffNormalEmissive = "Techniques/PBR/PBRDiffNormalEmissive.xml";
			public const string PBR_PBRDiffNormalEmissiveAlpha = "Techniques/PBR/PBRDiffNormalEmissiveAlpha.xml";
			public const string PBR_PBRMetallicRoughDiffNormalSpec = "Techniques/PBR/PBRMetallicRoughDiffNormalSpec.xml";
			public const string PBR_PBRMetallicRoughDiffNormalSpecEmissive = "Techniques/PBR/PBRMetallicRoughDiffNormalSpecEmissive.xml";
			public const string PBR_PBRMetallicRoughDiffNormalSpecEmissiveAlpha = "Techniques/PBR/PBRMetallicRoughDiffNormalSpecEmissiveAlpha.xml";
			public const string PBR_PBRMetallicRoughDiffSpec = "Techniques/PBR/PBRMetallicRoughDiffSpec.xml";
			public const string PBR_PBRMetallicRoughDiffSpecAlpha = "Techniques/PBR/PBRMetallicRoughDiffSpecAlpha.xml";
			public const string PBR_PBRNoTexture = "Techniques/PBR/PBRNoTexture.xml";
			public const string PBR_PBRNoTextureAlpha = "Techniques/PBR/PBRNoTextureAlpha.xml";
			public const string TerrainBlend = "Techniques/TerrainBlend.xml";
			public const string VegetationDiff = "Techniques/VegetationDiff.xml";
			public const string VegetationDiffUnlit = "Techniques/VegetationDiffUnlit.xml";
			public const string Water = "Techniques/Water.xml";
		}

		public static class Textures
		{
			public const string DefaultUI = "Textures/DefaultUI.png";
			public const string LUTIdentity = "Textures/LUTIdentity.xml";
			public const string Ramp = "Textures/Ramp.xml";
			public const string RampExtreme = "Textures/RampExtreme.xml";
			public const string RampWide = "Textures/RampWide.xml";
			public const string Spot = "Textures/Spot.xml";
			public const string SpotWide = "Textures/SpotWide.xml";
			public const string TouchInput = "Textures/TouchInput.png";
			public const string UI = "Textures/UI.xml";
			public const string Apple = "Textures/Apple.png";
			public const string Enemy3 = "Textures/Enemy3.png";
			public const string Enemy3weapon = "Textures/Enemy3weapon.png";
			public const string Enemy4DD = "Textures/Enemy4DD.png";
			public const string Grass = "Textures/Grass.dds";
			public const string Monkey = "Textures/Monkey.png";
			public const string Player1D = "Textures/Player1D.png";
			public const string Pyramid = "Textures/Pyramid.png";
			public const string TreeUV2 = "Textures/TreeUV2.png";
			public const string Xamarin = "Textures/xamarin.png";
		}

		public static class UI
		{
			public const string DefaultStyle = "UI/DefaultStyle.xml";
			public const string MessageBox = "UI/MessageBox.xml";
			public const string ScreenJoystick = "UI/ScreenJoystick.xml";
			public const string ScreenJoystick2 = "UI/ScreenJoystick2.xml";
		}

		public static class Particles
		{
			public const string Explosion = "Particles/Explosion.pex";
			public const string ExplosionPng = "Particles/Explosion.png";
			public const string HeavyMissileExplosion = "Particles/HeavyMissileExplosion.pex";
			public const string HeavyMissileExplosionPng = "Particles/HeavyMissileExplosion.png";
			public const string MissileTrace = "Particles/MissileTrace.pex";
			public const string PlayerExplosion = "Particles/PlayerExplosion.pex";
			public const string PlayerExplosionPng = "Particles/PlayerExplosion.png";
		}

		public static class Sounds
		{
			public const string BigExplosion = "Sounds/BigExplosion.wav";
			public const string MachineGun = "Sounds/MachineGun.wav";
			public const string Powerup = "Sounds/Powerup.wav";
			public const string SmallExplosion = "Sounds/SmallExplosion.wav";
		}

	}

}


